version: "3"
services:
  appserver:
    container_name: server
    hostname: localhost
    image: sregina/backend:latest
    ports:
      - "3000:3000"
    env_file:
      - env.env
    restart: unless-stopped
